@host=http://localhost:3000/api

### Crear un nuevo usuario
POST {{host}}/users
Content-Type: application/json

{
  "name": "Frank",
  "email": "frank@example.com",
  "password": "password123"
}

### Obtener todos los usuarios
GET {{host}}/users

### Obtener un usuario por ID
GET {{host}}/users/1

### Obtener un usuario por email
GET {{host}}/users/by-email?email=frank@example.com

### Actualizar un usuario por ID
PATCH {{host}}/users/1
Content-Type: application/json

{
  "name": "John222",
  "email": "john.doe222@example.com",
  "password": "password123222"
}

### Eliminar un usuario por ID
### 
DELETE {{host}}/users/1
### 
DELETE {{host}}/users/2
### 
DELETE {{host}}/users/3
