GET http://localhost:3000/api/users
token: autenticado

###
GET http://localhost:3000/api/users/1
token: autenticado

###
POST http://localhost:3000/api/users/register
Content-Type: application/json
token: autenticado

{
  "firstName": "Gio",
  "lastName": "m",
  "email": "gm@mail",
  "username": "user123",
  "password": "P4ss123",
  "birthdate": "1995-11-17",
  "nDni": "1542633"
}

###
POST  http://localhost:3000/api/users/login
Content-Type: application/json
token: autenticado

{
  "username": "user123",
  "password": "P4ss123"
}

###
GET http://localhost:3000/api/appointments

###
GET http://localhost:3000/api/appointments/1


###
POST http://localhost:3000/api/appointments/schedule
Content-Type: application/json
token: autenticado

{
  "date": "2024-11-21T10:00:00.000Z",
  "time": "09:15",
  "userId": 1,
  "description": "hernia lumbar"
}

###
PUT http://localhost:3000/api/appointments/cancel/1

