GET http://localhost:3000/users
token: autenticado

###
GET http://localhost:3000/users/1
token: autenticado

###
POST http://localhost:3000/users/register
Content-Type: application/json
token: autenticado

 {
        "firstName": "Gio",
        "lastName": "m",
        "email": "gm@mail",
        "username": "gm",
        "password": "122",
        "birthdate": "1995-11-17",
        "nDni": "1542633"
    }

###
POST  http://localhost:3000/users/login
Content-Type: application/json
token: autenticado

   {
  "username": "gm",
  "password": "122"
    }

###
GET http://localhost:3000/appointments

###
GET http://localhost:3000/appointments/1


###
POST http://localhost:3000/appointments/schedule
Content-Type: application/json
token: autenticado

{
  "date": "05-09-2024",
  "time": "09:15",
  "userId": 1
}

###
PUT http://localhost:3000/appointments/cancel/1

