### Create Appointment
POST http://localhost:3000/api/appointments
Content-Type: application/json

{
  "date": "2023-12-01T10:00:00.000Z",
  "description": "Annual check-up",
  "status": "PENDING",
  "patient": {
    "id": 2
  },
  "professional": {
    "id": 5
  }
}

### Get All Appointments
GET http://localhost:3000/api/appointments

### 
GET http://localhost:3000/api/appointments/pending-by-professional/9

### Fetch Last 10 Appointments
GET http://localhost:3000/api/appointments/last/3
Content-Type: application/json

### Get Appointment by ID
GET http://localhost:3000/api/appointments/1

### Update Appointment
PUT http://localhost:3000/api/appointments/1
Content-Type: application/json

{
  "date": "2024-11-22T10:00:00.000Z",
  "description": "Meeting with Team B"
}

### Cancel an Appointment
PATCH http://localhost:3000/api/appointments/cancel/1
Content-Type: application/json

### Delete Appointment
DELETE http://localhost:3000/api/appointments/1

### tempApptWhatsapp
POST http://localhost:3000/api/appointments/whatsapp
